### ISSUE TITLE
DFS Home Directory

### ISSUE THREAD

**Issue by devinziegler** [AminDaoudi/Final-Project#24]
Create a Domain group policy that moves W1 and W2 user profiles and home directories to a DFS share.

**Comment by Peytonvt** [comment]
Encountered error upon configuration

**Comment by devinziegler** [comment]
I would rather you not mess with this peyt

**Comment by Peytonvt** [comment]
copy that

**Comment by Peytonvt** [comment]
I'll get back to issues
