### ISSUE TITLE
Make last recording for Final Project

### ISSUE THREAD

**Issue by devinziegler** [AminDaoudi/Final-Project#30]
Milestone 3 recording will be the final recording of the project

**Comment by Peytonvt** [comment]
ready to record

**Comment by Peytonvt** [comment]
Does Saturday 7:00pm work for yall

**Comment by AminDaoudi** [comment]
I was thinking like 2pm we finish what's left for the to-do list/in progress work then we can aim to start our recording session at 7:00PM. Does that sound better?  (SATERDAY)

**Comment by Peytonvt** [comment]
Yah that sounds good, I work ti 6:30 but can swing over after
